language: node_js
node_js:
  - 12.16.0

#branches:
#  only:
#  - release

cache:
  directories:
    - node_modules

sudo: true
before_install:
  - sudo apt-get install sshpass

script:
  - yarn install
  - CI='' yarn build
  - bash .travis/deploy.sh
