version: "3.1"

name: mongo-dev

services:
  mongo:
    image: mongo:5.0
    container_name: mongo5-teemo
    command: --wiredTigerCacheSizeGB 0.5
    restart: always
    ports:
      # use env file in the same location of your compose.yml file.
      - "${MONGO_PORT}:27017"
    env_file:
      # relative to the location of your compose.yml file.
      - .env
    environment:
      TZ: Asia/Shanghai
    volumes:
      # relative to the location of your compose.yml file.
      - ./database/data:/data/db
      - ./database/entrypoint/:/docker-entrypoint-initdb.d/
