version: "3.5"

name: teemo

services:
  teemo:
    image: teemo-next:latest
    container_name: teemo-next
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - mongo-server
    networks:
      - webapp-network

  mongo-server:
    image: mongo:5.0
    container_name: mongo5-teemo
    command: --wiredTigerCacheSizeGB 0.5
    restart: always
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_DB_NAME: teemo_db
      MONGO_USER_NAME: teemo
      MONGO_USER_PASSWORD: teemo
    volumes:
      # relative to the location of your compose.yml file.
      - ./database/data:/data/db
      - ./database/entrypoint/:/docker-entrypoint-initdb.d/
    networks:
      - webapp-network  

networks:
  webapp-network:
    driver: bridge
