import type { Metadata } from "next";
import { ThemeProvider } from "@/components/global/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Head from "next/head";

import "./globals.css";

const title = "新标签页";

export const metadata: Metadata = {
  title,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <title>{title}</title>
      </Head>

      <body>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/fullpage-vertical-slider@latest/dist/style.css"
        />

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>

        <Toaster />
      </body>
    </html>
  );
}
